// <auto-generated />
using System;
using Academy.GestaoAlunos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.GestaoAlunos.Data.Migrations
{
    [DbContext(typeof(GestaoAlunosContext))]
    partial class GestaoAlunosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.AulaRealizada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("AulaRealizadas", (string)null);
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoVerificacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeDoAluno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TituloDoCurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Certificados", (string)null);
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.ProgressoAluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgressoAlunos", (string)null);
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.ProgressoAlunoCurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progresso")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("ProgressoAlunoCursos", (string)null);
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.AulaRealizada", b =>
                {
                    b.HasOne("Academy.GestaoAlunos.Domain.Entities.Matricula", "Matricula")
                        .WithMany("AulasRealizadas")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("Academy.GestaoAlunos.Domain.Entities.Matricula", null)
                        .WithOne("certificado")
                        .HasForeignKey("Academy.GestaoAlunos.Domain.Entities.Certificado", "MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.ProgressoAluno", b =>
                {
                    b.OwnsOne("Academy.GestaoAlunos.Domain.ObjectValue.HistoricoAprendizado", "HistoricoAprendizado", b1 =>
                        {
                            b1.Property<Guid>("ProgressoAlunoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TotalCursosConcluidos")
                                .HasColumnType("int")
                                .HasColumnName("TotalCursosConcluidos");

                            b1.Property<int>("TotalHoras")
                                .HasColumnType("int")
                                .HasColumnName("TotalHoras");

                            b1.HasKey("ProgressoAlunoId");

                            b1.ToTable("ProgressoAlunos");

                            b1.WithOwner()
                                .HasForeignKey("ProgressoAlunoId");
                        });

                    b.Navigation("HistoricoAprendizado")
                        .IsRequired();
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.ProgressoAlunoCurso", b =>
                {
                    b.HasOne("Academy.GestaoAlunos.Domain.Entities.Matricula", "Matricula")
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Academy.GestaoAlunos.Domain.Entities.Matricula", b =>
                {
                    b.Navigation("AulasRealizadas");

                    b.Navigation("certificado")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
